### ISSUE TITLE
Question: Critical Power

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#32]
Hi, sorry for this question using issues but I can't find a mailing list or another place for them.

I think I am missing something. You have the CP/W'/Tau model but how does this fit with existing FTP results. Say I do an FTP test using trainerroad.com and want to input the result. How can I go about doing this?

Also, it says in the critical power docs that it can determine these values from a ride but I cannot seem to find a way to do it. Could you please give me some pointers on these two issues please?

**Comment by alex-hhh** [comment]
**Disclarimer** The CP/FTP question creates quite heated argument on different forums, so I feel the need to say that I am not a sport scientist and the statements below are just my opinions, which were formed by reading a limited set of the available literature on the subject.  If you care about this, you should read the relevant scientific papers on this subject.

-----

From the theoretical point of view, the CP/W' and FTP/FRC have nothing in common, however both are mathematical models used to estimate your capability to do high intensity exercise.  They have different prescribed "test" workouts to determine these parameters.

From a practical point of view, you will find that CP and FTP are quite close to each other, usually CP is a few watts higher.  I personally believe that CP and FTP are the same, within the margin of error used to determine each one. Interestingly, I found no paper that discusses the statistical error for determining  your CP or FTP, e.g. all tests go with "your FTP is 250 watts" instead of saying "we can say with 95% confidence that your FTP is between 245 and 250 watts"._

BTW, to accurately determine CP/W' you will also need a short ~3 minute maximal workout, in addition to the long one used for the FTP.   I personally just determine my CP and use the same value for the FTP on my Garmin watch.

----

The ActivityLog2 application has two places where CP/W' are used: 

*First*, you can estimate CP/W' using a "best avg" trends chart.  The idea is that you would filter a set of activities (e.g. all bike rides within a time period) and the trends chart would find the maximal efforts among those bike rides and compute CP/W' for those.  This works on the assumption that the selected bike rides contain maximal efforts for various time periods.  If you only select "easy" rides, the code will compute CP/W' but they will not represent your true potential.

*Second* the application allows setting CP/W' values in the "Athlete/Edit Critical Power..." menu.  These have a date range and will apply to all session within the date range.  They are used to plot the "W'Bal" chart, which shows how energy is depleted / reconstituted during the ride.  You can enter any values here, I usually setup a trend chart with rides from the last 6 weeks and update CP/W' from time to time, but you could also go to a testing lab and enter the values provided by the lab.

There is no connection between the two.  The idea is that you can setup multiple trend charts for different seasons so the application will not know which are the CP/W' values you intend to use for your current session.  I planned some "auto CP" features, but never got to implement them.  See #14

----

Also, ActivityLog2 implements what is called the 2 parameter CP model.  There is also a 3 parameter CP model which can estimate your maximum power and account for power output for very short intervals, sub 10 seconds.  Being mathematical models your CP2 will be different than your CP3, but you would really need to read the literature to understand why.  Personally, I didn't believe the CP3 model to be useful, so I did not implemented, and I have too many ideas to work on already :-)

**Comment by alex-hhh** [comment]
BTW, thanks for taking the time to use ActivityLog2 and report problems with it.  I will try to do my best to answer any questions or fix any issues you report.
