### ISSUE TITLE
Tiles loaded far away from course

### ISSUE THREAD

**Issue by pmatos** [alex-hhh/ActivityLog2#38]
Now on HEAD, I just noticed that the tiles in the map are not being loaded properly. It felt initially that the tiles were not being loaded at all, but then I looked around and it seems tiles are being loaded (slowly) but quite far from the course itself, which is strange.

Where's the logic in the code to choose the tiles to load? And is there anyway to enable logging of the tile loading? So I understand if this is loading tiles at all or just idle?

**Comment by alex-hhh** [comment]
Is this something that just started happening?   There were a few changes to the map widget recently.  Could you perhaps check a few revisions back to see if the problem is still there?

The number of tiles that are waiting to be downloaded is displayed in the bottom left corner of the map where the legend is.  There should be a string like "ZL 12; BL 100".  ZL is the map zoom level, BL is the tile backlog -- the number of tiles that wait to be downloaded.  The "BL" part is missing if there are no outstanding tiles to be downloaded.

The code that manages tile downloading is in [map-tiles.rkt](https://github.com/alex-hhh/ActivityLog2/blob/master/rkt/widgets/map-widget/map-tiles.rkt), but it is relatively complex with several threads communicating using channels.   You can set `print-dbg-messages` to `#t` and recompile the file to get debugging info about the tile download printed to stdout.  But before you do that, it might be simpler to check if this is a regression introduced recently.

**Comment by alex-hhh** [comment]
Hi @pmatos , can you let me know if this is a regression or not? (see my previous comment).

The map tiles do load slowly (issue #28), and the download order will just fill up the map canvas area, but it will not necessarily start with the tiles under the GPS track.  However, I would like to know if the behavior you see is something that has changed recently, or if the map does not display correctly after the tiles have been downloaded.

Thanks,
Alex.

**Comment by alex-hhh** [comment]
Hi @pmatos , any updates on this issue? Thanks, Alex.

**Comment by pmatos** [comment]
Sorry, returned from hols last weeks and still trying to organize things... Will look at it this week.

**Comment by alex-hhh** [comment]
Closing issue as no response was received in a long time and I cannot make any progress on it.  Will reopen it I receive feedback on it.
