### ISSUE TITLE
Support keyboard shortcuts on Linux for copy/paste

### ISSUE THREAD

**Issue by misev** [alex-hhh/ActivityLog2#53]
In the text fields, e.g. when editing an activity, copy/paste/cut with Ctrl-C/Ctrl-V/Ctrl-X are not working on Linux.

I tried to figure out how to enable them, but the most I managed to do is add support for paste from [Primary selection buffer](https://shallowsky.com/blog/linux/x-selection.html) with middle mouse button click (usually the wheel nowadays).

```diff
diff --git a/rkt/al-widgets.rkt b/rkt/al-widgets.rkt
index 00e8e1d..a5e53ce 100644
--- a/rkt/al-widgets.rkt
+++ b/rkt/al-widgets.rkt
@@ -31,6 +31,8 @@
          "utilities.rkt"
          "widgets/main.rkt")

+(editor-set-x-selection-mode #t)
+
 (provide sport-selector%)
```

**Comment by alex-hhh** [comment]
Can you try if the following key board shortcuts work on Linux: C-y for paste, C-w for cut and Alt + w for copy?

**Comment by misev** [comment]
These work indeed, seems to be the Emacs scheme?

**Comment by alex-hhh** [comment]
These are the default key bindings that the Racket GUI library uses -- on Windows it's Ctrl-{C,X ,V} and I suspect on MacoS it is Command-{C,X,V}.  I will need to investigate on how to change the defaults, maybe I'll ask on the Racket lists first.

**Comment by alex-hhh** [comment]
I spent some time looking the Racket GUI source code, and it is not obvious to me where the "C-y" is bound.  Maybe this comes from the GTK library which is actually used?

After some internet search, I found that the keybindings used in GTK (Gnome?) applications can be configured, for example: https://unix.stackexchange.com/questions/342628/gnome-3-keybindings-in-source-where-are-ctrl-c-cut-copy-and-paste-defin, I was wondering if you could try that out?

**Comment by alex-hhh** [comment]
It turns out that the Emacs key bindings were the default for Linux in the Racket GUI libraries.  I talked with the Racket developers and they changed them to the more common Windows bindings.   This change will be available in the next Racket version (in about 3-4 months time) but it will also be available in the nightly snapshots in a day or so -- you will need to download a new Racket version and rebuild ActivityLog2 with it.

https://github.com/racket/gui/commit/b15f4c5f3e490ea3af6ff3911ddc8ff851781a3b

**Comment by misev** [comment]
Thanks for the swift fix! It seems very unlikely I would've been able to fix this myself.
