### ISSUE TITLE
Slowness on Session -> Charts

### ISSUE THREAD

**Issue by misev** [alex-hhh/ActivityLog2#56]
Not sure if it happens only for me (Ubuntu 20.04, Racket 7.9), the issue is best illustrated with a short video:

![Peek 2020-11-21 15-59](https://user-images.githubusercontent.com/4786324/99880739-92936280-2c15-11eb-8b2f-37a44879a79a.gif)

ActivityLog2 is pretty unresponsive while this processing is happening and uses 100% CPU. I build the latest code on master with `racket build.rkt`.

**Comment by alex-hhh** [comment]
To a certain extent, this is expected (and I'll go into some more details in a different comment), but can you set the environment variable `PLT_DISPLAY_BACKING_SCALE` to an integer value (1 or 2) and see if this improves performance?

Also, does this happen if you have 3-4 plots as well, or only when you have 12 as in the picture above?

**Comment by misev** [comment]
With up to 3 charts it works well, from 4 or more it starts having trouble. The `PLT_DISPLAY_BACKING_SCALE` didn't make a difference.

**Comment by alex-hhh** [comment]
I suggested trying out `PLT_DISPLAY_BACKING_SCALE` because this is a Linux specific settings, and there were reports on the racket-users list that setting this environment variable to an integer value, for high resolution displays makes GUI applications faster than when it is set to a real value, e.g 1.5.

I also see some performance degradation with a large number of plots on Windows, but not the 100% CPU.  Also this seems to be dependent on whether my laptop runs on battery (and the CPU is set to lower power) or it is plugged in when things run faster.

There is a lot of calculations and rendering going on when the mouse is hovered over the plots, and the internals of the plotting library are engineered for elegance and convenience rather than speed.   There are perhaps some improvements that could be done in ActivityLog2 to make things faster, but the benefit would be minimal.  There are more improvements that could be done in the Racket Plot library, but this would sacrifice maintainability for speed, and would also require a lot of effort.  Also, I am not sure what the overall benefit would be, given the amount of work required.

This brings us to the last point, about which something could be done.  What happens in your example, is that the AL2 code, in response to mouse-hover events, calculates the labels and requests a redraw.  For 12 plots, the calculations take a significant amount of time, and a new mouse event is received before the previous image is drawn.  This creates a cascade effect, where there are lots of mouse events and (slow) re-draw of plots making everything slower than it needs to be.

The solution is to have AL2 look at the timestamp of the mouse events, and, if they are too old, don't schedule redraws for them.  Another possibility is for the `canvas%` object to check if there are multiple draw requests queued, and discard them.

Before AL2 can look at timestamps for mouse events, this issue needs to be fixed: https://github.com/racket/gui/issues/132, as timestamps are not recorded currently, in a consistent fashion across platforms.  For `canvas%` redraw` optimizations, I would have to look at the Racket GUI source to see if anything can be done.

Unfortunately, improving this requires a lot of effort accros both the AL2 and the underlying Racket GUI library...

**Comment by alex-hhh** [comment]
Can you try the following patch to see if it improves things?   On my machine it will remove some of the intermediate redraws...

```diff
 rkt/session-inspector/inspect-graphs.rkt | 1 +
 1 file changed, 1 insertion(+)

diff --git a/rkt/session-inspector/inspect-graphs.rkt b/rkt/session-inspector/inspect-graphs.rkt
index f723b19..0464063 100644
--- a/rkt/session-inspector/inspect-graphs.rkt
+++ b/rkt/session-inspector/inspect-graphs.rkt
@@ -745,6 +745,7 @@
       (new plot-container% [parent parent] [columns 1]
            [min-height min-height]
            [style '()]))
+    (send graph-canvas lazy-refresh #t)
 
     (define/public (get-graph-canvas) graph-canvas)
 

```

**Comment by misev** [comment]
I think it improves the performance somewhat, although it's difficult to quantify how much.

It looked like the issue is that there is no filtering of the events, when they are more than can be rendered in real time. Intuitively I imagine it might be sufficient to scale down the event resolution so that at most one per 100-200ms is handled (some testing would be needed to determine this resolution). But I'm really not familiar with UI development, may be totally off.

It's a low priority thing in any case in my opinion. Maybe a small improvement is to put the charts drawing code on a separate thread so at least it doesn't block the whole application when you move around too fast with the mouse.

**Comment by alex-hhh** [comment]
Apart from using `lazy-refresh` I am not sure what else can be done to improve the performance, especially since the performance seems to be good on Windows, even with lots of plots.  I don't have the time to further investigate this, so I will close it.
