### ISSUE TITLE
Bug in Session view: Popup with labels is not updated.

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#63]
To reproduce:

1.  open sesion view
2.  open Edit Labels... dialog
3.  add new label and save
4. right click to add label to the session => the new label is not listed in this popup 

![UpdateBug](https://user-images.githubusercontent.com/4608274/109866383-7fa51b00-7c65-11eb-96e7-53dc72ddfd8d.gif)

**Comment by alex-hhh** [comment]
This is one of the many cases where the GUI consistency is still not maintained correctly when data changes. The workaround in this case is to use the "View/Refresh..." menu.  There are other cases when such inconsistencies happen, in particular the same thing would happen for the equipment.

I didn't work on these cases, because I considered this case to be infrequent: I would expect users to rarely define labels, and when they do, they either need to refresh the session view or re-open the session, but other than that, the label would be available.

----

The overall approach to GUI consistency is described in [gui-consistency.md](https://github.com/alex-hhh/ActivityLog2/blob/master/docs/gui-consistency.md), and for this to work we would need to:

* decide on the name for the new event, say `'labels-changed`
* update the labels editor to call `(log-event 'labels-changed #f)`, perhaps [when they are saved](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/dialogs/edit-labels.rkt#L167)
* add a demand-callback to the menu item to look for `'labels-changed` events.  The menu is created [here](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/widgets/tag-input-field.rkt#L160), but there are two classes derived from `tag-input-field%`: [label-input-field%](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/al-widgets.rkt#L222) and [equipment-input-field%](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/al-widgets.rkt#L269).   You can see how "listening" for these events is implemented by searching for `make-log-event-source`, for one example, see [here](https://github.com/alex-hhh/ActivityLog2/blob/391bf2b1cc2cc101149e1d0a093ae332bab8cf06/rkt/session-inspector/view-session.rkt#L411) -- note that each listening is done slightly differently, some use a separate thread, but in this case, we can just check in the demand-callback if the `'labels-changed` event was posted and update the menu before showing it.

**Comment by alex-hhh** [comment]
This is a corner case and a workaround is available.  Given that I don't have time to work in this, I will close it.
