### ISSUE TITLE
Wihslist: improvements in the Map view

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#66]
* Allow to select data series (e.g. speed or heard rate)
* Make the chart resizable
* Set default max zoom level to its maximum (18)

**Comment by alex-hhh** [comment]
Regarding making the chart resizeable, I pushed some changes to the master branch which do that (they also make the laps view resizeable), you can try them out.

Regarding making the max zoom level 18, I won't do that:  the application uses the free tier for downloading map tiles and zoom level 17 and 18 are generating on the fly.  I don't want to trigger some rate limit and have my application banned.  You can change the max zoom level in your own copy of the source if you want, but I will not add such a change to the main repository.

Regarding selecting the data series, this is somewhat more complex change, and I would also like to do it in a way that the GUI is not too complicated, but I have not worked out the details yet.

**Comment by TheGhost999** [comment]
Hi Alex,
Is there anymore movement on adding heart rate / elapsed time on the map data?
It could just be added to the popup data field in the elevation window,
I attach a screenshot also.

This would be very very useful information
![add-heart-rate-and-elapsed-time-to-map](https://github.com/alex-hhh/ActivityLog2/assets/32112188/0f385569-07d0-46ef-bd4c-3b039e74227a)
, hope maybe you can take a look at this?

Many thanks & keep up the great work Alex!

**Comment by alex-hhh** [comment]
Have you tried adding the elevation plot to the chart view?  The same elevation plot is available there, its called "Elevation (corrected) Color By Grade", and you can put it next to the Heart Rate plot to display HR at a certain point on a course.  To display elapsed time, you can select elapsed time from the "X Axis Shows" dropdown (there is "Time" which is time, excluding pauses, and "Elapsed Time" which includes pauses).

This allows showing any data series next to the elevation plot, and I planned to add a small map view to the Charts pane as well.

Changing the full map view, as you asked is more complex.  While you only want Heart Rate, it would make sense to add other things, such as Power or Pace, but this requires a mechanism to select what to display, which is more difficult to implement.

<img width="1128" alt="image" src="https://github.com/alex-hhh/ActivityLog2/assets/11592690/d9f58bb9-7f2e-44d0-876a-47ed444e5d83">

**Comment by TheGhost999** [comment]
hi Alex,
many thanks for your quick reply!

Excellent! Yes, this is very good, in Charts view.

But when you say; "  but this requires a mechanism to select what to display, which is more difficult to implement."
Maybe on the maps tab, could you add a few check boxes above the map (IE for HR), so a user could toggle the data on and off in the lower pane (Elevation chart?)

Here's a screenshot of my idea
Maybe it is difficult to do, but it is very very useful to be able to see on a full map where you are, and in that moment know your HR and pace /elapsed time etc.

Image below Alex

![hr-pace-to-elevation-on-map-tab](https://github.com/alex-hhh/ActivityLog2/assets/32112188/b3c0f0e5-df20-4aca-99ee-847eed37c038)


Maybe it is something you might be able to implement?
I'm no coder at all, but this feature on the map view would be so so useful Alex!

Keep up the great work
Cheers Alex
Best regards

**Comment by alex-hhh** [comment]
Yes, adding Heart Rate and Elapsed Time, as you suggested, would be quick to implement, but I want to implement a more flexible solution.

There are about 45 data series that are directly supported by ActivityLog2, plus additional ones from Connect IQ Garmin applications.  I would like a solution which allows the user to select the data fields they want displayed.  There are some additional complications because some data fields make sense only in pairs (e.g., Left and Right Pedal Smoothness).  

Putting 45 (or more) checkboxes above the map would not look nice and would waste space, and some thought and experimentation is needed on how to design a solution.    This part is more complex to implement.

It is not impossible, but this ActivityLog2 is a hobby project and I work on it in my spare time.  I already have more ideas than time to work on them, and this one was never a high enough priority enough to tackle.

----

However, adding a map view to the Graph panel is much easier to implement, and allows the user flexibility to show the data graphs they want (with only a limit on how big their monitor is).  This is still work in progress, but should be done this week or the next

<img width="1128" alt="image" src="https://github.com/alex-hhh/ActivityLog2/assets/11592690/2ea1f4d1-26a3-4645-abde-c45bfb1028da">

**Comment by TheGhost999** [comment]
Hi Alex,
Sorry for my late reply. 
Yes, I see and understand the points you are making, all very valid,, so much you could do, but only so many hrs in a day! 

Be great to see the next iteration of Activitylog come to life soon, with new map featured on the charts tab.
Keep up the great work Alex
Best Regards

**Comment by alex-hhh** [comment]
I added support for the map to be shown next to the graphs, and this is available in the most recent source code, you'll either need to build the application yourself or you can download the latest build from the link below.

Note that you'll need to add the map from the "Select Data Series" in the Graphs View for a session.  While I tested it a bit, there might still be problems with this, so please report here any problems you encounter.

https://dev.azure.com/alexharsanyi0641/ActivityLog2/_build/results?buildId=1440&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by alex-hhh** [comment]
Closing issue, release 2024.01 contains this fix.
