### ISSUE TITLE
HR data is missing in Lap Summary

### ISSUE THREAD

**Issue by idealist1508** [alex-hhh/ActivityLog2#80]
During the test for pr #79,  I noticed  another place where a  HR data is missing. 
![grafik](https://user-images.githubusercontent.com/4608274/139530036-10179e09-3c87-4ffb-9656-397b55b4dd88.png)

**Comment by idealist1508** [comment]
I suppose it necessary to update lap summary on import.

**Comment by alex-hhh** [comment]
The summary data also comes from the FIT file and, in this case, it looks like the HR is not recorded for the lengths.   The length rows which have HR data are because those were (re)calculated when the activity was edited.

I have a different "toto" to calculate summary data where it is missing, since some other devices also don't add it to the FIT file, but I didn't get around to implement it...

https://dev.azure.com/alexharsanyi0641/ActivityLog2/_workitems/edit/32/

**Comment by idealist1508** [comment]
I can't see a link. It is loading all the time.
![grafik](https://user-images.githubusercontent.com/4608274/139581028-4521af80-75ea-4df0-8951-3380a4b12a80.png)

I try to fix it at least for HR.

**Comment by alex-hhh** [comment]
There's not much in that linked issue either, just a note to calculate summary values in import. 

I keep some notes about future improvements on Azure DevOps -- although that project should be public...
