### ISSUE TITLE
CombinedPedalSmoothness XDATA Howto

### ISSUE THREAD

**Issue by Clashjo** [alex-hhh/ActivityLog2#94]
Getting .fit files from Garmin 520 head unit. I tried to follow the Readme for adding XDATA data series support to ActivityLog2 without luck.

The powermeter does not have PS L/R or TE L/R, it just sends combined pedaling smoothness.

So I added

    {
        "app_id" : "3910300977-1693476002",
        "app_name" : "Benji Powermeter",
        "fields" : [
            {
                "name" : "CombinedPedalSmoothness",
                "headline" : "Combined Pedal Smoothness (%)",
                "axis_label" : "Combined Pedal Smoothness (%)",
                "series" : "CombinedPedalSmoothness"
            }
        ]
    }
 to the xdata-defs.json definition file.

Created a new database for testing purpose, reloaded activity. Combined Pedal Smoothness remains not available. The app_id is the activity GUID I copied using ActivityLog2 Activity Menu.

**Comment by alex-hhh** [comment]
Looks like combined pedal smoothness is not an XDATA series but a native one (like power or heart rate), and there isn't support for it in ActivityLog2, since I never came across a data file with some example data.  If you are willing to share a FIT file with combined pedal smoothness data, I can add support for this data series.

---

Regarding XDATA series: these are only used for data produced by third party apps installed on the Garmin device from the Connect IQ store.  Unless you installed a separate application on your 520 for your power meter, there won't be an XDATA series for combined pedal smoothness.

"app_id" refers to the Connect IQ application ID (not the activity GUID) -- this can only be obtained from the database using a SQL query (or by inspecting the binary FIT file).  Also, the "series" name must match whatever the Connect IQ application uses for the XDATA series name (this again can be determined from the database or from inspecting the FIT file).

**Comment by Clashjo** [comment]
Alex, I sent you a FIT file with CPS data by e-mail as it looks like FIT file type may not shared on this forum. 

Golden Cheetah had identified the 'combined pedal smoothess' as XDATA. Hence my confusion. Thanks for your help

**Comment by alex-hhh** [comment]
Hi @Clashjo , I did not receive the file via email (checked the spam folder to).  Have you sent it to the correct address? It's AlexHarsanyi@gmail.com 

You can also create a ZIP file containing the FIT file and attach it to this issue.  However, please be aware that this issue tracker is public, accessible by anyone.

**Comment by alex-hhh** [comment]
Thanks for sending me a sample file.  I added support for combined pedal smoothness and it is now in the master branch.   You can build it yourself, or, if you prefer, you can download Windows binaries from:

https://dev.azure.com/alexharsanyi0641/ActivityLog2/_build/results?buildId=1388&view=artifacts&pathAsName=false&type=publishedArtifacts

Can you please let me know if this works for you?
Thanks,
Alex.

**Comment by Clashjo** [comment]
Hi Alex,

It works. I didn't notice any problem, or omission.

Just lap average Combined Pedaling Smoothness (%) could eventually be added to the Session tab 'Laps' summary page.

PS -- It looks like the Pedal Balance (%) data series cannot be selected in Session tab 'MeanMax' chart. Does this limitation also exist on your side ?

**Comment by alex-hhh** [comment]
> Just lap average Combined Pedaling Smoothness (%) could eventually be added to the Session tab 'Laps' summary page.

This feature is a bit obscure, but you can select a row in the laps view, then select the "View/Setup Columns..." menu from the top menu bar, you'll get a dialog box that can edit the columns visible in the laps view, you can select the combined pedal smoothness form there, and there are many other fields you can display.

Note that this setting is specific to the sport type (e.g., you can show different things for running and cycling)

The same approach works for columns visible in the Activity List.

> 
Hi Alex,

It works. I didn't notice any problem, or omission.

Just lap average Combined Pedaling Smoothness (%) could eventually be added to the Session tab 'Laps' summary page.

PS -- It looks like the Pedal Balance (%) data series cannot be selected in Session tab 'MeanMax' chart. Does this limitation also exist on your side ?

Yes, this was just an omission, I added that option as well.

**Comment by alex-hhh** [comment]
Closed as fixed based on feedback from the reporter
