### ISSUE TITLE
Failed to import: #(struct:exn:fail fit-file: bad file CRC #<continuation-mark-set>)

### ISSUE THREAD

**Issue by gerhardol** [alex-hhh/ActivityLog2#96]
Message when importing:
Failed to import F:\links\gf255\Activity\2023-12-11-20-04-18.fit: #(struct:exn:fail fit-file: bad file CRC #<continuation-mark-set>)

For all activities with GPS data since updating my Garmin Forerunner 255 to 17.21 on Nov 20 (at that time beta, now official).
(An activity can be provided  by email.)

Something is changed in .fit.

**Comment by alex-hhh** [comment]
Could you send me a FIT file that has this problem?  My FR945 and Edge130 are up to date and the fit files from them import without problems, so I am not sure what is happening in your case Alex. On 12 Dec 2023, at 7:06 am, Gerhard Olsson ***@***.***> wrote:﻿
Message when importing:
Failed to import F:\links\gf255\Activity\2023-12-11-20-04-18.fit: #(struct:exn:fail fit-file: bad file CRC #)
For all activities with GPS data since updating my Garmin Forerunner 255 to 17.21 on Nov 20 (at that time beta, now official).
(An activity can be provided  by email.)
Something is changed in .fit.

**Comment by gerhardol** [comment]
The branch you pushed works well for me. Thanks!

**Comment by alex-hhh** [comment]
The fix has been merged to master.  For reference, the problem was that the FIT file seems to contain additional data at the end, in excess of what the file length in the FIT header specifies.  The code was changed to verify the CRC only on the number of bytes specified in the FIT header.  I'm not sure what the extra data in the FIT file actually is.
